//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ingemmet.CommonService.WebService.Services.Security.Model
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateUserActiveDirectoryResponse", Namespace="http://schemas.datacontract.org/2004/07/Ingemmet.CommonService.WebService.Service" +
        "s.Security.Model")]
    public partial class ValidateUserActiveDirectoryResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Ingemmet.CommonService.Entity.Models.UserModel DataField;
        
        private bool IsValidField;
        
        private Ingemmet.CommonService.WebService.Model.MessageResponse StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ingemmet.CommonService.Entity.Models.UserModel Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValid
        {
            get
            {
                return this.IsValidField;
            }
            set
            {
                this.IsValidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ingemmet.CommonService.WebService.Model.MessageResponse Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserOfficeActiveDirectoryResponse", Namespace="http://schemas.datacontract.org/2004/07/Ingemmet.CommonService.WebService.Service" +
        "s.Security.Model")]
    public partial class UserOfficeActiveDirectoryResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string OfficeField;
        
        private Ingemmet.CommonService.WebService.Model.MessageResponse StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Office
        {
            get
            {
                return this.OfficeField;
            }
            set
            {
                this.OfficeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ingemmet.CommonService.WebService.Model.MessageResponse Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserActiveDirectoryResponse", Namespace="http://schemas.datacontract.org/2004/07/Ingemmet.CommonService.WebService.Service" +
        "s.Security.Model")]
    public partial class UserActiveDirectoryResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Ingemmet.CommonService.Entity.Models.UserModel DataField;
        
        private Ingemmet.CommonService.WebService.Model.MessageResponse StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ingemmet.CommonService.Entity.Models.UserModel Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ingemmet.CommonService.WebService.Model.MessageResponse Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
}
namespace Ingemmet.CommonService.Entity.Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserModel", Namespace="http://schemas.datacontract.org/2004/07/Ingemmet.CommonService.Entity.Models")]
    public partial class UserModel : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DateField;
        
        private string DepartmentField;
        
        private string EmailAddressField;
        
        private string ExternalAccessTokenField;
        
        private string IdField;
        
        private string NameField;
        
        private string PositionField;
        
        private string RequestNumberField;
        
        private string RoleNameField;
        
        private string SamAccountNameField;
        
        private long UserIDSecurityField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department
        {
            get
            {
                return this.DepartmentField;
            }
            set
            {
                this.DepartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalAccessToken
        {
            get
            {
                return this.ExternalAccessTokenField;
            }
            set
            {
                this.ExternalAccessTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                this.PositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestNumber
        {
            get
            {
                return this.RequestNumberField;
            }
            set
            {
                this.RequestNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName
        {
            get
            {
                return this.RoleNameField;
            }
            set
            {
                this.RoleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SamAccountName
        {
            get
            {
                return this.SamAccountNameField;
            }
            set
            {
                this.SamAccountNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserIDSecurity
        {
            get
            {
                return this.UserIDSecurityField;
            }
            set
            {
                this.UserIDSecurityField = value;
            }
        }
    }
}
namespace Ingemmet.CommonService.WebService.Model
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageResponse", Namespace="http://schemas.datacontract.org/2004/07/Ingemmet.CommonService.WebService.Model")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ingemmet.CommonService.Entity.Models.UserModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ingemmet.CommonService.WebService.Services.Security.Model.ValidateUserActiveDirectoryResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ingemmet.CommonService.WebService.Services.Security.Model.UserOfficeActiveDirectoryResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ingemmet.CommonService.WebService.Services.Security.Model.UserActiveDirectoryResponse))]
    public partial class MessageResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short CodeField;
        
        private string MessageField;
        
        private object OtherCodeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object OtherCode
        {
            get
            {
                return this.OtherCodeField;
            }
            set
            {
                this.OtherCodeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IActiveDirectoryWebService")]
public interface IActiveDirectoryWebService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActiveDirectoryWebService/ValidateCredentials", ReplyAction="http://tempuri.org/IActiveDirectoryWebService/ValidateCredentialsResponse")]
    Ingemmet.CommonService.WebService.Services.Security.Model.ValidateUserActiveDirectoryResponse ValidateCredentials(string username, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActiveDirectoryWebService/ValidateCredentials", ReplyAction="http://tempuri.org/IActiveDirectoryWebService/ValidateCredentialsResponse")]
    System.Threading.Tasks.Task<Ingemmet.CommonService.WebService.Services.Security.Model.ValidateUserActiveDirectoryResponse> ValidateCredentialsAsync(string username, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActiveDirectoryWebService/ValidateUsername", ReplyAction="http://tempuri.org/IActiveDirectoryWebService/ValidateUsernameResponse")]
    Ingemmet.CommonService.WebService.Services.Security.Model.ValidateUserActiveDirectoryResponse ValidateUsername(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActiveDirectoryWebService/ValidateUsername", ReplyAction="http://tempuri.org/IActiveDirectoryWebService/ValidateUsernameResponse")]
    System.Threading.Tasks.Task<Ingemmet.CommonService.WebService.Services.Security.Model.ValidateUserActiveDirectoryResponse> ValidateUsernameAsync(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActiveDirectoryWebService/GetUserOffice", ReplyAction="http://tempuri.org/IActiveDirectoryWebService/GetUserOfficeResponse")]
    Ingemmet.CommonService.WebService.Services.Security.Model.UserOfficeActiveDirectoryResponse GetUserOffice(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActiveDirectoryWebService/GetUserOffice", ReplyAction="http://tempuri.org/IActiveDirectoryWebService/GetUserOfficeResponse")]
    System.Threading.Tasks.Task<Ingemmet.CommonService.WebService.Services.Security.Model.UserOfficeActiveDirectoryResponse> GetUserOfficeAsync(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActiveDirectoryWebService/FindByUsername", ReplyAction="http://tempuri.org/IActiveDirectoryWebService/FindByUsernameResponse")]
    Ingemmet.CommonService.WebService.Services.Security.Model.UserActiveDirectoryResponse FindByUsername(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActiveDirectoryWebService/FindByUsername", ReplyAction="http://tempuri.org/IActiveDirectoryWebService/FindByUsernameResponse")]
    System.Threading.Tasks.Task<Ingemmet.CommonService.WebService.Services.Security.Model.UserActiveDirectoryResponse> FindByUsernameAsync(string username);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IActiveDirectoryWebServiceChannel : IActiveDirectoryWebService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ActiveDirectoryWebServiceClient : System.ServiceModel.ClientBase<IActiveDirectoryWebService>, IActiveDirectoryWebService
{
    
    public ActiveDirectoryWebServiceClient()
    {
    }
    
    public ActiveDirectoryWebServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ActiveDirectoryWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ActiveDirectoryWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ActiveDirectoryWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Ingemmet.CommonService.WebService.Services.Security.Model.ValidateUserActiveDirectoryResponse ValidateCredentials(string username, string password)
    {
        return base.Channel.ValidateCredentials(username, password);
    }
    
    public System.Threading.Tasks.Task<Ingemmet.CommonService.WebService.Services.Security.Model.ValidateUserActiveDirectoryResponse> ValidateCredentialsAsync(string username, string password)
    {
        return base.Channel.ValidateCredentialsAsync(username, password);
    }
    
    public Ingemmet.CommonService.WebService.Services.Security.Model.ValidateUserActiveDirectoryResponse ValidateUsername(string username)
    {
        return base.Channel.ValidateUsername(username);
    }
    
    public System.Threading.Tasks.Task<Ingemmet.CommonService.WebService.Services.Security.Model.ValidateUserActiveDirectoryResponse> ValidateUsernameAsync(string username)
    {
        return base.Channel.ValidateUsernameAsync(username);
    }
    
    public Ingemmet.CommonService.WebService.Services.Security.Model.UserOfficeActiveDirectoryResponse GetUserOffice(string username)
    {
        return base.Channel.GetUserOffice(username);
    }
    
    public System.Threading.Tasks.Task<Ingemmet.CommonService.WebService.Services.Security.Model.UserOfficeActiveDirectoryResponse> GetUserOfficeAsync(string username)
    {
        return base.Channel.GetUserOfficeAsync(username);
    }
    
    public Ingemmet.CommonService.WebService.Services.Security.Model.UserActiveDirectoryResponse FindByUsername(string username)
    {
        return base.Channel.FindByUsername(username);
    }
    
    public System.Threading.Tasks.Task<Ingemmet.CommonService.WebService.Services.Security.Model.UserActiveDirectoryResponse> FindByUsernameAsync(string username)
    {
        return base.Channel.FindByUsernameAsync(username);
    }
}
