//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendGrid.Helpers.Mail
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailAddress", Namespace="http://schemas.datacontract.org/2004/07/SendGrid.Helpers.Mail")]
    public partial class EmailAddress : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EmailField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
}
namespace Ingemmet.ServiciosDigitales.Entity.Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MethodResponseModelOfint", Namespace="http://schemas.datacontract.org/2004/07/Ingemmet.ServiciosDigitales.Entity.Models" +
        "")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SendGrid.Helpers.Mail.EmailAddress))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SendGrid.Helpers.Mail.EmailAddress[]))]
    public partial class MethodResponseModelOfint : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodeField;
        
        private string MessageField;
        
        private object OtherCodeField;
        
        private int ResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object OtherCode
        {
            get
            {
                return this.OtherCodeField;
            }
            set
            {
                this.OtherCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IEmailWcfService")]
public interface IEmailWcfService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailWcfService/SendSingleEmail", ReplyAction="http://tempuri.org/IEmailWcfService/SendSingleEmailResponse")]
    Ingemmet.ServiciosDigitales.Entity.Models.MethodResponseModelOfint SendSingleEmail(string apiKey, long sistemaId, SendGrid.Helpers.Mail.EmailAddress from, SendGrid.Helpers.Mail.EmailAddress to, string subject, string body, bool addCco, SendGrid.Helpers.Mail.EmailAddress cco);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailWcfService/SendSingleEmail", ReplyAction="http://tempuri.org/IEmailWcfService/SendSingleEmailResponse")]
    System.Threading.Tasks.Task<Ingemmet.ServiciosDigitales.Entity.Models.MethodResponseModelOfint> SendSingleEmailAsync(string apiKey, long sistemaId, SendGrid.Helpers.Mail.EmailAddress from, SendGrid.Helpers.Mail.EmailAddress to, string subject, string body, bool addCco, SendGrid.Helpers.Mail.EmailAddress cco);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailWcfService/SendSingleEmailToMultipleRecipients", ReplyAction="http://tempuri.org/IEmailWcfService/SendSingleEmailToMultipleRecipientsResponse")]
    Ingemmet.ServiciosDigitales.Entity.Models.MethodResponseModelOfint SendSingleEmailToMultipleRecipients(string apiKey, long sistemaId, SendGrid.Helpers.Mail.EmailAddress from, SendGrid.Helpers.Mail.EmailAddress[] tos, string subject, string body, bool addCco, SendGrid.Helpers.Mail.EmailAddress cco);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailWcfService/SendSingleEmailToMultipleRecipients", ReplyAction="http://tempuri.org/IEmailWcfService/SendSingleEmailToMultipleRecipientsResponse")]
    System.Threading.Tasks.Task<Ingemmet.ServiciosDigitales.Entity.Models.MethodResponseModelOfint> SendSingleEmailToMultipleRecipientsAsync(string apiKey, long sistemaId, SendGrid.Helpers.Mail.EmailAddress from, SendGrid.Helpers.Mail.EmailAddress[] tos, string subject, string body, bool addCco, SendGrid.Helpers.Mail.EmailAddress cco);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailWcfService/ResendEmail", ReplyAction="http://tempuri.org/IEmailWcfService/ResendEmailResponse")]
    Ingemmet.ServiciosDigitales.Entity.Models.MethodResponseModelOfint ResendEmail(long mailDeliveryId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailWcfService/ResendEmail", ReplyAction="http://tempuri.org/IEmailWcfService/ResendEmailResponse")]
    System.Threading.Tasks.Task<Ingemmet.ServiciosDigitales.Entity.Models.MethodResponseModelOfint> ResendEmailAsync(long mailDeliveryId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IEmailWcfServiceChannel : IEmailWcfService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EmailWcfServiceClient : System.ServiceModel.ClientBase<IEmailWcfService>, IEmailWcfService
{
    
    public EmailWcfServiceClient()
    {
    }
    
    public EmailWcfServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public EmailWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EmailWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EmailWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Ingemmet.ServiciosDigitales.Entity.Models.MethodResponseModelOfint SendSingleEmail(string apiKey, long sistemaId, SendGrid.Helpers.Mail.EmailAddress from, SendGrid.Helpers.Mail.EmailAddress to, string subject, string body, bool addCco, SendGrid.Helpers.Mail.EmailAddress cco)
    {
        return base.Channel.SendSingleEmail(apiKey, sistemaId, from, to, subject, body, addCco, cco);
    }
    
    public System.Threading.Tasks.Task<Ingemmet.ServiciosDigitales.Entity.Models.MethodResponseModelOfint> SendSingleEmailAsync(string apiKey, long sistemaId, SendGrid.Helpers.Mail.EmailAddress from, SendGrid.Helpers.Mail.EmailAddress to, string subject, string body, bool addCco, SendGrid.Helpers.Mail.EmailAddress cco)
    {
        return base.Channel.SendSingleEmailAsync(apiKey, sistemaId, from, to, subject, body, addCco, cco);
    }
    
    public Ingemmet.ServiciosDigitales.Entity.Models.MethodResponseModelOfint SendSingleEmailToMultipleRecipients(string apiKey, long sistemaId, SendGrid.Helpers.Mail.EmailAddress from, SendGrid.Helpers.Mail.EmailAddress[] tos, string subject, string body, bool addCco, SendGrid.Helpers.Mail.EmailAddress cco)
    {
        return base.Channel.SendSingleEmailToMultipleRecipients(apiKey, sistemaId, from, tos, subject, body, addCco, cco);
    }
    
    public System.Threading.Tasks.Task<Ingemmet.ServiciosDigitales.Entity.Models.MethodResponseModelOfint> SendSingleEmailToMultipleRecipientsAsync(string apiKey, long sistemaId, SendGrid.Helpers.Mail.EmailAddress from, SendGrid.Helpers.Mail.EmailAddress[] tos, string subject, string body, bool addCco, SendGrid.Helpers.Mail.EmailAddress cco)
    {
        return base.Channel.SendSingleEmailToMultipleRecipientsAsync(apiKey, sistemaId, from, tos, subject, body, addCco, cco);
    }
    
    public Ingemmet.ServiciosDigitales.Entity.Models.MethodResponseModelOfint ResendEmail(long mailDeliveryId)
    {
        return base.Channel.ResendEmail(mailDeliveryId);
    }
    
    public System.Threading.Tasks.Task<Ingemmet.ServiciosDigitales.Entity.Models.MethodResponseModelOfint> ResendEmailAsync(long mailDeliveryId)
    {
        return base.Channel.ResendEmailAsync(mailDeliveryId);
    }
}
